# -*- coding: utf-8 -*-
"""Mini project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ud9Pj3tc0WNsFMLIJnizTkv8LbN3INyN
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/messy_customer_sales_data.csv')

# Question 1:Load the CSV file into Pandas and display the first 5 rows of the dataset.
df.head(5)

# Question 2:Display the last 5 rows of the dataset.
df.tail(5)

# Question 3:Find the number of rows and columns in the dataset.
print("Rows:", len(df))
print("Columns:", len(df.columns))

# Question 4:Display the column names of the dataset.
df.columns

# Question 5:Use one command to check data types, missing values, and memory usage.
print(df.info())

# Question 6:Select and display Customer_ID, Name, City, and Purchase_Amount columns.

df[["Name","Customer_ID","City","Purchase_Amount"]]

# Question 7:Display details of customers who belong to the city CHENNAI.
df.loc[df["City"]==" CHENNAI "]

# Question 8:Display all customers whose Country is India.
df[df["Country"]=="India"]

# Question 9:Display customers whose Purchase_Amount is greater than 30,000.
df[df["Purchase_Amount"]>30000]

# Question 10:Count how many customers are male and female.
df['Gender'].value_counts()

# Question 11:Identify how many missing values are present in each column.
df.isnull().sum()

# Question 12:Find customers whose Purchase_Amount is missing.
df.isnull().sum().Purchase_Amount

# Question 13: Replace missing values in Purchase_Amount with the average value.
x = df["Purchase_Amount"].mean()
df.fillna({"Purchase_Amount":x},inplace = True)

df.isnull().sum().Purchase_Amount

# Question 14:Check how many values are missing in the City column.
df.isnull().sum().City

# Question 15:Remove rows where Age is missing
df.dropna(subset =['Age'])

# Question 16:Convert all values in the Gender column to Male/Female format.
df['Gender'] = df['Gender'].str.strip().str.lower().map({
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female'
})

# Question 17: Clean the City column (uppercase and remove extra spaces).
df['City'] = df['City'].str.strip().str.upper()

# QUESTION 18:Standardize the Country column so all values become India.
df['Country'] = 'India'

# Question 19:Convert Signup_Date column into datetime format.
df['Signup_Date']= pd.to_datetime(df['Signup_Date'] )

# Question 20:Convert Last_Purchase_Date column into datetime format.
myvar = pd.to_datetime(df['Last_Purchase_Date'],format = 'mixed' )
print(myvar)

# Question 21:Find the average Purchase_Amount of all customers
average = df['Purchase_Amount'].mean()
print(average)

# Question 22:Find the average Purchase_Amount city-wise.
average=df.groupby('City')['Purchase_Amount'].mean()
print(average)

# Question 23:Count how many customers belong to each City.
City =  df['City'].value_counts()
print(City)

# Question 24:Find customers whose Purchase_Amount is greater than the overall average.
average = df['Purchase_Amount'].mean()

overall = df[df["Purchase_Amount"]>average]

print("average:",average)

print("overall:",overall)

# Question 25: Create a new column Customer_Type (High Value / Regular)
average = df['Purchase_Amount'].mean()


df['Customer_Type'] = df['Purchase_Amount'].apply(
    lambda x: 'High Value' if x > average else 'Regular'
)
print("Overall Average:", average)
print(df)

"""**#Complete my project.**"""